debug: false
blocked-commands:
  - "plugins"
  - "pl"
  - "version"
  - "ver"
  - "about"
  - "icanhasbukkit"
  - "bukkit:plugins"
  - "bukkit:pl"
  - "bukkit:version"
  - "bukkit:ver"
  - "bukkit:about"

plugins:
  enabled: true
  paper:
    - "Geyser-Spigot"
    - "ViaVersion"
    - "ProtocolLib"
  bukkit:
    - "EssentialsX"
    - "WorldEdit"
    - "LuckPerms"
    - "Vault"
    - "PlaceholderAPI"
    - "CoreProtect"
    - "WorldGuard"

unknown-msg: "Unknown command. Type \"/help\" for help."