debug: false
blocked-commands:
  - "plugins"
  - "pl"
  - "version"
  - "ver"
  - "about"
  - "icanhasbukkit"
  - "bukkit:plugins"
  - "bukkit:pl"
  - "bukkit:version"
  - "bukkit:ver"
  - "bukkit:about"

plugins:
  enabled: true
  hover-tooltips: true
  paper:
    enabled:
      - "Geyser-Spigot"
      - "ViaVersion"
      - "ProtocolLib"
    legacy:
      - "ViaBackwards"
      - "OldCombatMechanics"
    disabled:
      - "SkinsRestorer"
      - "AuthMe"
  bukkit:
    enabled:
      - "EssentialsX"
      - "WorldEdit"
      - "LuckPerms"
      - "Vault"
      - "PlaceholderAPI"
    legacy:
      - "PermissionsEx"
      - "GroupManager"
    disabled:
      - "CoreProtect"
      - "WorldGuard"

unknown-msg: "Unknown command. Type \"/help\" for help."