name: PluginSpoofer
version: 1.0.1
main: cn.nekopixel.pluginspoofer.Main
api-version: 1.20
depend: [packetevents]

commands:
  pluginspoofer:
    description: "PluginSpoofer 主命令"
    aliases: [ps]
    permission: pluginspoofer.admin

permissions:
  pluginspoofer.admin:
    description: "允许使用 PluginSpoofer 管理命令"
    default: op